tpm2: Add missing prototypes for function added to Marshal.c
This patch fixes the following compilation error detected (only) on
Fedora 32/s390x:

tpm2/Marshal.c:1129:1: error: no previous prototype for 'TPMI_TDES_KEY_BITS_Marshal' [-Werror=missing-prototypes]
 1129 | TPMI_TDES_KEY_BITS_Marshal(TPMI_TDES_KEY_BITS *source, BYTE **buffer, INT32 *size)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
tpm2/Marshal.c:1370:1: error: no previous prototype for 'TPMS_SIG_SCHEME_SM2_Marshal' [-Werror=missing-prototypes]
 1370 | TPMS_SIG_SCHEME_SM2_Marshal(TPMS_SIG_SCHEME_SM2 *source, BYTE **buffer, INT32 *size)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
tpm2/Marshal.c:1798:1: error: no previous prototype for 'TPMS_SIGNATURE_SM2_Marshal' [-Werror=missing-prototypes]
 1798 | TPMS_SIGNATURE_SM2_Marshal(TPMS_SIGNATURE_SM2 *source, BYTE **buffer, INT32 *size)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>